package com.company.sumaApp;


/**
* com.company.sumaApp/suma.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from suma.idl
* viernes 11 de diciembre de 2020 11:47:44 PM COT
*/

public interface suma extends com.company.sumaApp.sumaOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity
{
} // interface suma
