package com.company.sumaApp;


/**
* com.company.sumaApp/sumaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from suma.idl
* viernes 11 de diciembre de 2020 11:47:44 PM COT
*/

public interface sumaOperations 
{
  int sumar (int primernumero, int segundonumero);
  void shutdown ();
} // interface sumaOperations
