package com.company.sumaApp;

/**
* com.company.sumaApp/sumaHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from suma.idl
* viernes 11 de diciembre de 2020 11:47:44 PM COT
*/

public final class sumaHolder implements org.omg.CORBA.portable.Streamable
{
  public com.company.sumaApp.suma value = null;

  public sumaHolder ()
  {
  }

  public sumaHolder (com.company.sumaApp.suma initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.company.sumaApp.sumaHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.company.sumaApp.sumaHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.company.sumaApp.sumaHelper.type ();
  }

}
